### ISSUE TITLE
Create deb package acceptable for Debian distro

### ISSUE THREAD

**Issue by ped7g** [z00m128/sjasmplus#267]
This is meta issue tracking progress toward final goal, official .deb package.

at this moment I'm **guessing** these need to be addressed:
- [ ] #235 
- [ ] split into actionable tasks comments in this [fork commit](https://github.com/terrex/sjasmplus/commit/678c8afe3b186099bd83679467441dbf705594a7) and add them as new issues to this tracking meta issue
- [ ] probably start on separate branch as the early debian/xyz files will be too crude to sit on master branch for long period of time

**Comment by ped7g** [comment]
Did some progress on this with the help of copilot, but ran out of free quota till next.

If anyone has .deb packaging experience and wants to help to guide this, check the branch content.

**Comment by ped7g** [comment]
How it's going:
- **created [repo](https://salsa.debian.org/ped7g/sjasmplus) on salsa.debian.org** which will contain the Debian packaging, it will be separate from this repo (didn't push the current WIP yet, hopefully soon)
- in this WIP branch the debian/copyright is full of nonsense generated by GHCP (wrong licenses, wrong persons, wrong years), so do NOT reuse these
- slowly progressing toward some initial version, still need to figure out how repackage .tar.gz with patched content for Debian, ideally generating it from git repo content, at least for a start. Maybe later adding support for z00m's release src packages to have both git and tarbal support.
- may need few patches here at upstream, like making examples utf8 only (to clear linter log)
- which means new release tag so I can build the final package from patched version
- need to open sjasmplus ITP bug (Intention To Package) on Debian tracker, but day has too few hours, if somebody will open it for me, I will be very grateful.

and the list goes on... 😅

**Comment by ped7g** [comment]
Debian ITP bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1136128

**Comment by ped7g** [comment]
Salsa CI vs submodules - possible hint how to deal with that (could be incorrect, verify/validate):
```yaml
# .salsa-ci.yml
variables:
  # Tell the GitLab runner to fetch submodules
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  script:
    # The GIT_SUBMODULE_STRATEGY variable handles this, but you could also do it manually:
    # - git submodule update --init --recursive 
    
    # Install build dependencies listed in debian/control
    - apt-get update
    - apt-get install -y build-essential devscripts equivs
    - mk-build-deps -i -t "apt-get -y" debian/control
    
    # Build the package
    - dpkg-buildpackage -us -uc -b
```
